config/routes.rb
Rails.application.routes.draw do
  resources :users

  root to: 'visitors#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/events' => 'events#index', as: :events
  get '/events/:firebase_id' => 'events#show', as: :event
  post '/events/create' => 'events#create', as: :create_event

  post '/comments/create' => 'comments#create'

  post '/pictures/upload' => 'pictures#upload', as: :upload_picture
  get '/pictures/downloadd/:name' => 'pictures#download', as: :download_picture
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base


  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.token = auth['credentials']['token']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by_firebase_id(params[:firebase_id])
  end

  def create
    event = Event.new(permitted_params[:event])
    base_uri = 'https://eavesdrop.firebaseio.com/'
    firebase = Firebase::Client.new(base_uri)
    response = firebase.push("events", { name: event.name,
                                         latitude: event.latitude || 0,
                                         longitude: event.longitude|| 0 })
    event.firebase_id = response.body["name"]
    event.save
    firebase.push("events/#{event.firebase_id}/users", current_user.uid)
    redirect_to event_path(event.firebase_id)
  end

  private

  def permitted_params
    params.permit(event: [:name, :latitude, :longitude, :firebase])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def upload
    uploaded_file = params[:picture]
    new_path, name = tmp_path
    FileUtils.mv uploaded_file.path, new_path

    render json: { image: download_picture_path(name) }
  end

  def download
    disposition = params[:disposition]
    disposition ||= 'attachment'
    name = params[:name]
    send_file "#{Rails.root}/uploaded_pictures/" + name, filename: name,
      disposition: disposition
  end

  def tmp_path
    loop do
      name = (1..12).map { '0123456789abcdefghijklmnopqrstuvwxyz'.chars.sample }.join
      tmp_path = Rails.root.join('uploaded_pictures', name)
      return [tmp_path.to_s, name] unless File.exist? tmp_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if session[:user_id]
      redirect_to events_path
    else
      redirect_to '/auth/facebook'
    end
  end

  def create
    if session[:user_id]
      redirect_to events_path
    else
      auth = request.env["omniauth.auth"]
      user = User.where(:provider => auth['provider'],
                        :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
      reset_session
      session[:user_id] = user.id
      redirect_to events_path, :notice => 'Signed in!'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    redirect_to events_path if session[:user_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_map.html.erb
<script>
var siberia = new google.maps.LatLng(60, 105);
var newyork = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
var menlo_park = new google.maps.LatLng(37.4875929, -122.1462192);
var browserSupportFlag =  new Boolean();
var map;

function initialize(latitude, longitude, zoom) {
  var myOptions = {
    zoom: zoom || 10,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    center: menlo_park,
    styles: mapstyle
  };
  map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);

  if (!latitude) {
    // Try W3C Geolocation (Preferred)
    if(navigator.geolocation) {
      browserSupportFlag = true;
      navigator.geolocation.getCurrentPosition(function(position) {
        $('#form_latitude').val(position.coords.latitude);
        $('#form_longitude').val(position.coords.longitude);
        initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);

        map.panTo(initialLocation);
        map.setZoom(16);

        marker = new google.maps.Marker({
          position: initialLocation,
          map: map
        });

        loadEvents();
      }, function() {
        handleNoGeolocation(browserSupportFlag);
      });
    }
    // Browser doesn't support Geolocation
    else {
      browserSupportFlag = false;
      handleNoGeolocation(browserSupportFlag);
    }
  } else {
    initialLocation = new google.maps.LatLng(latitude, longitude);
    map.setCenter(initialLocation);
    marker = new google.maps.Marker({
      position: initialLocation,
      map: map
    });
  }

  function handleNoGeolocation(errorFlag) {
    if (errorFlag == true) {
      alert("Geolocation service failed.");
      initialLocation = newyork;
    } else {
      alert("Your browser doesn't support geolocation. We've placed you in Siberia.");
      initialLocation = siberia;
    }
    map.setCenter(initialLocation);
  }

  google.maps.event.addListener(map, 'click', function( event ){
    console.log("Latitude: "+event.latLng.lat()+" "+", longitude: "+event.latLng.lng() );
  });
}

function smoothZoom (map, max, cnt) {
  if (cnt >= max) {
        return;
    }
  else {
    z = google.maps.event.addListener(map, 'zoom_changed', function(event){
        google.maps.event.removeListener(z);
        smoothZoom(map, max, cnt + 1);
    });
    setTimeout(function(){map.setZoom(cnt)}, 80); // 80ms is what I found to work well on my system -- it might not work well on all systems
  }
}

mapstyle = [{"featureType":"water","stylers":[{"visibility":"on"},{"color":"#acbcc9"}]},{"featureType":"landscape","stylers":[{"color":"#f2e5d4"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#c5c6c6"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#e4d7c6"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#fbfaf7"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#c5dac6"}]},{"featureType":"administrative","stylers":[{"visibility":"on"},{"lightness":33}]},{"featureType":"road"},{"featureType":"poi.park","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":20}]},{},{"featureType":"road","stylers":[{"lightness":20}]}];

</script>

app/views/events/index.html.erb
<div id="map-canvas" style="top: 0;left: 0px;bottom: 0px;right: 0px;height: auto;position: absolute;margin-top: 50px;"></div>
<div>
  <!-- <input type='text' id='eventName' placeholder='Message'> -->
</div>
<%= render 'map' %>
<div style="position: absolute; left: 50%; width: 400px; top: 48px;">
  <div id="top-box" class="slider-two closed" style="background-color: white; height:500px;">
    <div class="row" style="color: gray; text-align: center;font-family: Pacifico; font-size:30px; margin-left:0px !important;margin-right:0px !important;">Nearby Events:</div>
    <div id="nearbyEvents" class="" style="">

    </div>
  </div>
</div>


<form accept-charset="UTF-8" action="/events/create" class="new_event" id="new_event" method="post" novalidate="novalidate">
<div style="position: absolute; left: 50%; width: 500px; bottom: -2px;">
  <div id="bottom-box" class="slider closed" style="background-color: rgb(79, 130, 195);padding-top:0px; height:100px;">
    <div class="" style="text-align:center" style="margin-left:0px !important;margin-right:0px !important;">
      <div class="row" style="color:#EAEAEA; font-family: Pacifico; font-size:30px; margin-left:0px !important;margin-right:0px !important;">New Event:</div>
      <div class="col-md-8" style="width:72.666667%;padding-right: 0px;padding-left: 32px;">
        <input class="form-control string optional" id="event_name" name="event[name]" type="text" style="border-radius:0px;">
      </div>
      <div class="col-md-4" style="width:24.333333%; padding:0px;">
        <input name="commit" type="submit" value="Add Event" class="btn btn-success" style="border-radius:0px;">
      </div>
    <input id="form_latitude" name="event[latitude]" type="hidden">
    <input id="form_longitude" name="event[longitude]" type="hidden">
    </div>
  </div>
</div>
</form>


<script>
var initialLocation;

<%
  graph = Koala::Facebook::API.new(current_user.token)
  friends = graph.get_connections("me", "friends").map { |f| f['id'] }
%>

var friendsIds = $.parseJSON('<%= raw friends.to_json.html_safe %>');



$(function(){
  initialize();
  $( "#bottom-box" ).hover(function() {
    $( this ).toggleClass( 'closed' );
  });
  $( "#top-box" ).hover(function() {
    $( this ).toggleClass( 'closed' );
  });
})

function shuffle(array) {
  var currentIndex = array.length, temporaryValue, randomIndex ;

  // While there remain elements to shuffle...
  while (0 !== currentIndex) {

    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;

    // And swap it with the current element.
    temporaryValue = array[currentIndex];
    array[currentIndex] = array[randomIndex];
    array[randomIndex] = temporaryValue;
  }

  return array;
}

var comments = [];
function addComment(marker, comment) {

  html = '<div style="min-width: 190px;">' +
            '<div style="display:inline-block; height: 20px;">' +
              '<img src="https://graph.facebook.com/v2.2/' + comment.user_id + '/picture" style="height: 20px;">' +
            '</div>' +
            '<div style="margin-left: 21px;margin-top: -21px;" class="text-muted">' + comment.name + '</div>';
  if (comment.image) {
    html += '<img style="width: 150px" src="' + comment.image + '">';
  } else {
    html += '<div style="margin-left: 5px; margin-top: 4px;">'+comment.message+'</div></div>';
  }
  comments.unshift([marker, html]);
  shuffle(comments);
}

function showComment(marker, html) {
    marker.newComments.content = html;

    marker.setAnimation(google.maps.Animation.BOUNCE);
    setTimeout(function() { marker.setAnimation(null); }, 750);
    marker.newComments.open(map, marker);
    setTimeout(function() { marker.newComments.close(); }, 3000);
}

setInterval(function() {
  if (comments.length > 0) {
    comment = comments.shift();
    comments.push(comment);
    showComment(comment[0], comment[1]);
  }
}, 6000);

function loadEvents(){
  var nearbyEvents = [];
  var eventsRef = new Firebase('https://eavesdrop.firebaseio.com/events');

  eventsRef.on('child_added', function(snapshot) {
    var event = snapshot.val();
    displayEvents(snapshot.key(), event.name, event.latitude, event.longitude, event);

    setTimeout( function(){ displayNearbyEvents(snapshot.key(), event);}, 1500);
  });

  function displayNearbyEvents(id, event){
    var distance = Math.sqrt(Math.pow(initialLocation.k - event.latitude, 2) + Math.pow(initialLocation.B - event.longitude, 2)) * 111000;

    var content = '<div id="content'+id+'" class="events-list" style="margin-left: 0; margin-right: 0">'+
      '<div class="row">'+
        '<div class="col-md-6" style="font-size: 18px;font-weight: 100;">'+
          '<i class="fa fa-map-marker" style="color: lightblue; margin-right: 7px;"></i><a href="/events/'+id+'" >'+event.name+
        '</a></div>'+
        '<div class="col-md-6" style="text-align: right;">'+
          '<i class="fa fa-group" style="color: gray;"></i><span event_id="' + id + '" style="color: green">...</span>' +
        '</div>'+
      '</div>' +
      '<div class="row">'+
        '<div class="col-md-6" style="text-align: left">'+
          '<div class="pictures" style="" event_id="' + id + '"></div>' +
        '</div>' +
        '<div class="col-md-6" style="text-align: right;">'+
          +parseInt(distance)+' meters away.'+
        '</div>'+
      '</div>' +
    '</div>';

    $('#nearbyEvents').append(content);

  }

  function displayEvents(id, name, lat, lng, event) {
    var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';

    var contentString = '<div id="hook'+id+'" style="font-size: 18px;font-weight: 100; min-width: 200px"><i class="fa fa-map-marker" style="color: lightblue; margin-right: 7px;"></i>' + name + '</div>';

    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(lat, lng),
      map: map,
      animation: google.maps.Animation.DROP,
      title: name,
      icon: iconBase + 'schools_maps.png',
      // icon: "<%= image_path('location-pointer2.png') %>",
      info: new google.maps.InfoWindow({
        content: contentString,
        zIndex: 10000
      }),
      newComments: new google.maps.InfoWindow({
        content: '<h3> comment here </h3>',
        maxWidth: 400,
        disableAutoPan: true
      })
    });

    google.maps.event.addListener(marker, 'mouseover', function() {
      marker.info.open(map, marker);
    });

    google.maps.event.addListener(marker, 'mouseout', function() {
      marker.info.close();
    });

    google.maps.event.addListener(marker, 'click', function(){
      location.href = 'events/'+id;
    });

    var usersRef = new Firebase('https://eavesdrop.firebaseio.com/events/'+id+'/users');

    var activeUsers = 0;
    var friendsOnThisEvent = [];
    var friendsPictures = '';
    usersRef.on('child_added', function(snapshot) {
      user_id = snapshot.val();
      if ($.grep(friendsIds, function(friendId) { return friendId == user_id }).length > 0 &&
          $.grep(friendsOnThisEvent, function(friendId) { return friendId == user_id }).length == 0) {
        friendsOnThisEvent.push(user_id);
        html = marker.info.content;
        picture = '<div style="display: inline-block"><img class="img-circle" style="width: 30px; height: 30px" src="https://graph.facebook.com/v2.2/' + user_id + '/picture"></div>';
        friendsPictures += picture;
        html += picture;
        marker.info.content = html;
      }

      activeUsers += 1;
    });

    setInterval(function() {
      $('span[event_id="'+id+'"]').html(activeUsers +' Active');
      $('.pictures[event_id="'+id+'"]').html(friendsPictures);
    }, 1000);

    //=========================================================================
    //COMMENT LOADING

    var commentsRef = new Firebase('https://eavesdrop.firebaseio.com/events/'+id+'/comments');

    // var newItems = false;

    commentsRef.on('child_added', function(snapshot) {
      // if (!newItems) return;
      var comment = snapshot.val();
      addComment(marker, comment);
    });


    commentsRef.once('value', function(messages) {
      newItems = true;
    });
  }
}

function randomEvents(){
  var eventsRef = new Firebase('https://eavesdrop.firebaseio.com/events');
  for(i = 0; i < 3; i++){
    var name = "TEST EVENT";
    if(i==0){
      name = "Free Sweets!"
    } else if(i == 1){
      name = "PartyHere!"
    } else {
      name = "Facebook Tour"
    }

    if(i < 3){
      var event = eventsRef.push({
        name: name,
        latitude: (37.484116 + (Math.random()-0.5)*0.005),
        longitude: (-122.147793 + (Math.random()-0.5)*0.005),
      });
    } else {
      var event = eventsRef.push({
        name: name,
        latitude: (37.484116 + (Math.random()-0.5)*0.005),
        longitude: (-122.147793 + (Math.random()-0.5)*0.005),
      });
    }
    console.log(event.path.m[1]);
    key = event.path.m[1];
    var childCommentsRef = new Firebase('https://eavesdrop.firebaseio.com/events/'+key+'/comments');
    var usersRef = new Firebase('https://eavesdrop.firebaseio.com/events/'+key+'/users');

    if(i==0){
      childCommentsRef.push({
        message: "I wonder how the hackathon competition is going.",
        name: "Amaya Quiroz",
        user_id: "1157319713"
      });
      usersRef.push("1157319713");


      childCommentsRef.push({
        message: "I have no idea what a hackathon is.",
        name: "Louis Gustavson",
        user_id: "1157319714"
      });
      usersRef.push("1157319714");

      childCommentsRef.push({
        message: "A competition where you create awesome applications!.",
        name: "Amaya Quiroz",
        user_id: "1157319713"
      });
      usersRef.push("1157319713");
    } else if(i==1) {
      childCommentsRef.push({
        message: "Food is awesome at this party!.",
        name: "Amy Han",
        user_id: "1157319720"
      });
      usersRef.push("1157319720");

      childCommentsRef.push({
        message: "I know right!?",
        name: "Itxasne Llamosas",
        user_id: "1157319650"
      });
      usersRef.push("1157319650");      

      childCommentsRef.push({
        message: "This burrito is freaking delicious!.",
        name: "Amy Han",
        user_id: "1157319720"
      });
      usersRef.push("1157319720");
    } else if(i==2) {
      childCommentsRef.push({
        message: "Facebook HQ is awesome!",
        name: "Willy Rafael",
        user_id: "1157315678"
      });
      usersRef.push("1157315678");

      childCommentsRef.push({
        message: "More like FOODBOOK!",
        name: "Jo Jones",
        user_id: "1157315679"
      });
      usersRef.push("1157315679");

      childCommentsRef.push({
        message: "Or FACEFOOD!",
        name: "Willy Rafael",
        user_id: "1157315678"
      });
      usersRef.push("1157315678");

      childCommentsRef.push({
        message: "No.",
        name: "Jo Jones",
        user_id: "1157315679"
      });
      usersRef.push("1157315679");
    }
  }
}
</script>

app/views/events/show.html.erb
<div class="row" style="">
  <div class="col-md-7" style="box-shadow: -3px -32px 64px 2px black;padding-right: 35px; z-index: 3;border-right: 4px dashed white;">
    <h3 style="margin-bottom: 24px;">
      <%= @event.name %>'s Feed
    </h3>
    <div class="row">
      <div class="col-md-12" id="chat_column">

        <div id="form_comment" class="row" style="margin-bottom:15px;">
          <div class="col-md-12" style="position: relative;">
            <textarea style="width: 87%; margin-left: 69px;" class="form-control" type="text" id="messageInput" placeholder="Type here..."></textarea>
            <input id="picture-input" type="file" name="file" style="position: absolute; top: -1000px; display: none;" />
          </div>

          <button id="submit-btn" class="btn btn-info " style="width: 54px; height: 54px">
            <span class="glyphicon glyphicon-pencil" style="font-size: 24px" aria-hidden="true"></span>
          </button>
          <button id="add-picture" class="btn btn-primary " style="width: 54px; height: 54px">
            <span class="glyphicon glyphicon-camera" style="font-size: 24px" aria-hidden="true"></span>
          </button>
        </div>
        <div  id="timeline-chat" class="timeline-centered" style="margin-bottom: 10px">

          <div id="comments_container">
          </div>

        </div>

      </div>
    </div>
  </div>

  <div class="col-md-5" style="padding: 0px; z-index: 1;">
    <div id="map_well" class="well" style="height: 700px; margin-bottom: 0px; padding: 0px;">
      <div id="map-canvas" style="height: 100%;"></div>
      <%= render 'map' %>
    </div>
  </div>

</div>

<script>

$(function(){
  initialize(<%= @event.latitude %>, <%= @event.longitude %>, 14);

  if(navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      latitude = position.coords.latitude;
      longitude = position.coords.longitude;

      event_latitude = parseFloat("<%= @event.latitude %>");
      event_longitude = parseFloat("<%= @event.longitude %>");

      distance = Math.sqrt(Math.pow(latitude - event_latitude, 2) + Math.pow(longitude - event_longitude, 2)) * 111000;

      if (distance < 500) {
        $('#form_comment').show();
      }

    }, function() {});
  }
});

$(window).load(function(){ // On load
      $('#map_well').css({'height':(($(window).height() - 51))+'px'});
      $('#timeline-chat').css({'height':(($(window).height() - 215))+'px'});
    });
    $(window).resize(function(){ // On resize
      $('#map_well').css({'height':(($(window).height() - 51))+'px'});
      $('#timeline-chat').css({'height':(($(window).height() - 215))+'px'});

    });

$( "#submit-btn" ).on( "click", function() {
  submit();
});

$('#messageInput').keypress(function(e) {
    if(e.which == 13) {
      submit();
    }
});

var commentsRef = new Firebase('https://eavesdrop.firebaseio.com/events/'+"<%= @event.firebase_id %>"+'/comments');
var usersRef = new Firebase('https://eavesdrop.firebaseio.com/events/'+"<%= @event.firebase_id %>"+'/users');

function submit(){
  var name;
  var id;
  var text = $('#messageInput').val();
  name = "<%= current_user.name %>";
  score = 0;
  time = new Date();
  commentsRef.push({
    name: name,
    message: text,
    user_id: "<%= current_user.uid %>",
    time: time.toJSON()
  });
  $('#messageInput').val('');
  usersRef.push("<%= current_user.uid %>");
}

var newComments = false;

commentsRef.on('child_added', function(snapshot) {
  comment = snapshot.val();
  time = comment.time;
  html = '<article class="timeline-entry">' +
            '<div class="timeline-entry-inner">' +
              '<div class="timeline-icon bg-success">' +
                '<img src="https://graph.facebook.com/v2.2/' + comment.user_id + '/picture" class="img-circle">' +
              '</div>' +
              '<div class="timeline-label" hidden>' +
                '<div style="display: inline-block">' +
                  '<h2><a href="http://www.facebook.com/' + comment.user_id + '">' + comment.name + '</a></h2>' +
                '</div>' +
                '<div class="pull-right" style="display: inline-block">' +
                  '<span class="time text-muted" style="font-size: 11px;margin-left: 5px;" time="' + time + '">' + moment(time).fromNow() + '</span>' +
                '</div>';

  if (comment.image) {
    html += '<img style="width: 500px" src="' + comment.image + '">';
  } else {
    html += '<p style="font-size: 15px;">' + comment.message + '</p>';
  }

  html += '</div>' + '</div>' + '</article>';

  $('#comments_container').prepend(html);

  if (newComments){
    $('.timeline-label:first').slideDown();
    $('.timeline-label:first').addClass('fadeWhite');
  }else{
    $('.timeline-label:first').show();
  }

});

commentsRef.once('value', function(messages) {
  newComments = true;
});

$('#add-picture').on('click', function(e) {
  e.preventDefault();
  $('#picture-input').click();
});

$('#picture-input').on('change', function() {
  files = event.target.files;
  file = files[0];
  data = new FormData();
  data.append('picture', file);
  $.ajax({
    url: '/pictures/upload',
    type: 'POST',
    data: data,
    processData: false,
    contentType: false,
    success: function(data, textStatus, jqXHR) {
      time = new Date();
      commentsRef.push({
        name: "<%= current_user.name %>",
        message: '',
        user_id: "<%= current_user.uid %>",
        time: time.toJSON(),
        image: data.image
      });
    },
  });
});

setInterval(function() {
  $.each($('.time'), function(index, div) {
    time = $(div).attr('time');
    $(div).text(moment(time).fromNow());
  });
}, 10000);
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top" id="nav_bar" style="background-color:#AE0000;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Dropscout', root_path, class: 'navbar-brand', style: 'color:#EAEAEA; font-size:30px; margin-right:17px; font-family:Pacifico' %>
    </div>
    <div class="collapse navbar-collapse">

      <div class="navbar-right">
        <ul class="nav navbar-nav" style="font-familty: 'Open Sans',sans-serif;">
          <%= render 'layouts/navigation_links' %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li ><%= link_to 'Events', events_path, class: 'hoverToHighlight' %></li>

  <% if controller_name == 'events' && action_name == 'index' %>
    <li style="margin-top: 0px">
    </li>
  <% end %>

  <li  ><%= link_to 'Sign out', signout_path, class: 'hoverToHighlight' %></li>

<% else %>
  <li  ><%= link_to 'Sign in', signin_path, class: 'hoverToHighlight' %></li>
<% end %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

app/views/visitors/index.html.erb
<script>
  $('#nav_bar').addClass('hidden');
  
</script>
<div class="container" id="main-title-bg">
  <div class="row" style="padding-top:150px;">
    <div class="col-md-10">
      <h1 style="font-family: Pacifico; font-size:150px; color: #EAEAEA; text-shadow: 0px 0px 25px #000;" id="main_title">
        <span style="color:#AE0000; text-shadow: 0px 0px 20px #000;">Drop</span>scout <span class="glyphicon glyphicon-map-marker" style="font-size:95px; color:#AE0000; margin-left: 5px;"></span>
      </h1>
      <h2 style="font-family: 'Overlock', serif; color: #EAEAEA; text-align:left; text-shadow: 0px 0px 19px #000; margin-left:12px">
        Know what's going on, instantly. 
      </h2>
    </div>
    <div class="col-md-2"></div>
  </div>
  <div class="row" style="padding-top:30px; text-align:center;">
    <a href="<%= signin_path %>" style="float: left; margin-left: 20px; text-shadow: 0px 0px 20px #000;">
      <img src="https://s3-eu-west-1.amazonaws.com/poledancedictionary.com/images/login_fb.png" alt=""></img>
    </a>
  </div>
</div>